###
post http://localhost:3001/task
Content-Type: application/json

{
  "title": "estudar JavaScript",
  "description": "Aprofundar meus conhecimentos em "
}

###
GET http://localhost:3001/task

###

GEt http://localhost:3001/task/ec61bdd0-0fdc-4e62-bc9d-27aa3237a67a

###

GEt http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4

###
PATCH http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4
Content-Type: application/json

{
  "title": "Estudar prisma atualizado",
  "description": "Descrição também foi alterada"
}

###
PATCH http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4
Content-Type: application/json

{
  "title": "Prisma"
}

###
PATCH http://localhost:3001/task/bf8698e9-d875-4c43-ae34-4e0ab1710c47
Content-Type: application/json

{
  "description": "estudar js para aprofundar os conhecimento"
}

###
PATCH http://localhost:3001/task/done/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4
Content-Type: application/json
###

PATCH http://localhost:3001/task/4d9a1983-525d-417d-9689-2876d592b297/done

###

PATCH http://localhost:3001/task/ec61bdd0-0fdc-4e62-bc9d-27aa3237a67a/todo

###

DELETE http://localhost:3001/task/ec61bdd0-0fdc-4e62-bc9d-27aa3237a67a



