###
post http://localhost:3001/task
Content-Type: application/json

{
  "title": "Estudar Prisma",
  "description": "Aprofundar meus conhecimentos em Prisma"
}

###
GET http://localhost:3001/task

###

GEt http://localhost:3001/task/ec61bdd0-0fdc-4e62-bc9d-27aa3237a67a

###

GEt http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4

###
PATCH http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4
Content-Type: application/json

{
  "title": "Estudar prisma atualizado",
  "description": "Descrição também foi alterada"
}

###
PATCH http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4
Content-Type: application/json

{
  "title": "Prisma"
}

###
PATCH http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4
Content-Type: application/json

{
  "description": "estudar prisma e aprofundar os conheciemtnos"
}

###
PATCH http://localhost:3001/task/done/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4
Content-Type: application/json
###

PATCH http://localhost:3001/task/f8d935bc-ca5b-4fb0-94cf-a531d89ac0b4/done



